name = "EISCATData"
uuid = "41864403-1ac0-48c6-a62c-c20a831807e0"
version = "0.1.0"
authors = ["Zijin Zhang <zijin@ucla.edu> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FieldViews = "ff5a1669-b1f2-423e-bbd7-b7fa0f7e0224"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Madrigal = "30ac0af5-7056-44d2-a45c-266d747295e6"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"

[compat]
Dates = "1"
FieldViews = "0.3"
HDF5 = "0.17"
Madrigal = "0.1.2"
Match = "2"
julia = "1.10"
